- name: NGINX | Trying to create the nginx rooot directory
  file:
    path: "{{ nginx_root_dir }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0755
    state: directory

- name: NGINX | Trying to create the nginx conf directory
  file:
    path: "{{ nginx_conf_dir }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0755
    state: directory

- name: NGINX | Trying to create the nginx conf.d directory
  file:
    path: "{{ nginx_confd_dir }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0755
    state: directory

- name: NGINX | Trying to create the nginx log directory
  file:
    path: "{{ nginx_log_dir }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0755
    state: directory

- name: NGINX | Trying to create the nginx static directory
  file:
    path: "{{ nginx_static_dir }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0755
    state: directory