- name: CentOS | Trying to install the dependencies in CentOS 7.0
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - gcc-c++
    - autoconf
    - automake

- name: CentOS | Trying to install the libraries in CentOS 7.0
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - zlib
    - zlib-devel
    - openssl
    - openssl-devel
    - pcre-devel

- name: NGINX | Trying to init nginx service in CentOS 7.0
  template:
    src: nginx.service.j2
    dest: "/usr/lib/systemd/system/nginx.service"
    mode: 0754
    force: yes
  notify:
    - Systemctl Daemon Reload
    - Start Nginx