- name: Ubuntu | Trying to install the dependencies in Ubuntu 14.04
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - g++
    - make

- name: Ubuntu | Trying to install the libraries in Ubuntu 14.04
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libpcre3-dev
    - zlib1g-dev
    - libssl-dev

- name: NGINX | Trying to init nginx service in Ubuntu 14.04
  template:
    src: nginx.initd.j2
    dest: "/etc/init.d/nginx.service"
    mode: 0754
    force: yes
  notify:
    - start nginx